server:
  port: 53639

spring:
  application:
    name: menu-service
  mvc: # data.sql
    hiddenmethod:
      filter:
        enabled: 'true'
  cloud:
    config:
      enabled: false

  sql:
    init:
      mode: always

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/menu?serverTimezone=Asia/Seoul
    username: root
    password: 1234

  jpa:
    show-sql: 'false'
    properties:
      hibernate:
        format_sql: true
        query.in_clause_parameter_padding: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate.ddl-auto: create
    defer-datasource-initialization: true # data.sql

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  #    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}} ?? ??
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

logging:
  #  charset:
  #    console: UTF-8
  #    file: UTF-8
  level:
    root: info
    org.hibernate.SQL: debug

greeting:
  message: Welcome to the Simple E-Commerce.

global:
  jwt-token:
    signer: ${NOCTEM_JWT_SIGNER}
  value: local-menu